### ISSUE TITLE
Static NVM_DIR export name

### ISSUE THREAD

**Issue by gatzjames** [adamisntdead/DevMyMac#4]
Hi really nice configuration!
In the script: https://github.com/adamisntdead/DevMyMac/blob/master/setup.sh#L67
Should this be requested from the user?

**Comment by adamisntdead** [comment]
Ah nice catch, I originally used this script for myself so I evidently forgot to change it, I will do it now, Thanks so much for your support!!

**Comment by adamisntdead** [comment]
Did that now! Thanks!
